### PR TITLE
add Treafik 2 to reverse proxy documentation

### PR DESCRIPTION
**Pull request by szaimen**
Close https://github.com/nextcloud/all-in-one/discussions/543

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by szaimen** [comment]
@macaussie does this PR look good to you? :)

**Comment by szaimen** [comment]
@macaussie when you give your go, I'll merge this :)

**Comment by njakes** [comment]
This is fantastic timing.  Just today I blew away my old nextcloud-vm setup and am rebuilding my server with traefik and your AIO script.  I am a bit stuck with getting it to work behind traefik though.  It looks like this is getting pretty close. Completely new to reverse proxies.

**Comment by njakes** [comment]
Do there need to be back ticks inside "Host(`domain.com`)"?

**Comment by szaimen** [comment]
Hello @njakes please open a new discussion if you should need help setting this up.

**Pull request merged**
