### PR TITLE
update postgres to 14.2

### LINKED ISSUE #265: Feature: Upgrade to PostgreSQL 14
Upgrade from PostgreSQL 13 to 14.2. PostgreSQL 14.x is supposed to be a huge performance boost and may help with Nextcloud at a performance level.

### PR DESCRIPTION
**Pull request by szaimen**
Close #265

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by juliushaertl** [comment]
One thing I'm not sure about but as far as I remember major Postgres upgrades would require to run pg_upgrade in some way. Did you test this with an upgrade of existing data?

**Comment by szaimen** [comment]
> One thing I'm not sure about but as far as I remember major Postgres upgrades would require to run pg_upgrade in some way. Did you test this with an upgrade of existing data?

There is already a built-in update procedure (that I built) which works, afaik ;)

**Comment by juliushaertl** [comment]
All right, then good to go from my side 😉

**Review by juliushaertl — APPROVED** [review]

**Comment by szaimen** [comment]
Merging then, thanks! :)

**Pull request merged**
