### PR TITLE
increase opcache buffer to 64

### PR DESCRIPTION
**Pull request by szaimen**
Close https://github.com/nextcloud/all-in-one/issues/772

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by szaimen** [comment]
@MichaIng does this look good?

**Comment by 2020Sanoj** [comment]
I think it could also directly set to 64, then the chance to hit this limit would be much smaller

**Comment by szaimen** [comment]
Thanks for the answer! So even 32 is not reasonable?

**Comment by MichaIng** [comment]
Hard to say absolute. If really an app contains that large amount of strings in it's code/GUI, it can be reasonable. But I cannot imaging that any app does so.

Would be great to be able to look into the strings buffer and see which strings from which scripts it contains.

I'll have a look into Nextcloud data, to probably find a location where apps can store temporary data/scripts. Strings from the database are AFAIK not hold in that buffer (like such contained in the generated HTML documents.

**Comment by szaimen** [comment]
Okay, so I would reduce it to 16 again and ask people in the future to fist debug it?

**Comment by MichaIng** [comment]
I'd suggest to use 32 MiB for the following reason:
- Nextcloud is able to use max 64 MiB of the regular OPcache. I tested this once with installing and browsing the GUI of literally all available apps, and hit close to 64 MiB.
- So 32 MiB for interned strings is safe to use without a risk to hit the default overall OPcache size of 128 MiB, when only Nextcloud is used.

I'll also suggest this for https://github.com/nextcloud/server/pull/32902.

**Comment by szaimen** [comment]
thanks! will do so :)

**Pull request merged**
