### PR TITLE
apache - expose udp for http3 to work

### PR DESCRIPTION
**Pull request by szaimen**
Close https://github.com/nextcloud/all-in-one/discussions/2825

### CODE REVIEW

**Comment by Zoey2936** [comment]
I just want to say that WebKit sometimes throws an error when the alt-srv header is sent, but http3 is not reachable

**Comment by szaimen** [comment]
> I just want to say that WebKit sometimes throws an error when the alt-srv header is sent, but http3 is not reachable

so what to do then?

**Comment by Zoey2936** [comment]
> > I just want to say that WebKit sometimes throws an error when the alt-srv header is sent, but http3 is not reachable
> 
> so what to do then?

it is a very rare issue, the only thing would be to disable http3 or opening the ports

**Comment by szaimen** [comment]
Will Webkit bug completely out if the port 443/udp is not available and http3 enabled or is it a minor issue like a cosmetic one?

**Comment by Zoey2936** [comment]
> Will Webkit bug completely out if the udp is not available and http3 enabled or is it a minor issue like a cosmetic one?

sometimes it will show that the webserver is unavailable, but as I said this is very rare

**Comment by szaimen** [comment]
> sometimes it will show that the webserver is unavailable, but as I said this is very rare

I see. then lets hope that they fix it in a future update :)

**Review by Zoey2936 — APPROVED** [review]

**Pull request merged**
