### PR TITLE
apache documentation - make the push proxy work

### PR DESCRIPTION
**Pull request by szaimen**
Close part of https://github.com/nextcloud/all-in-one/issues/834

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Review by 2020Sanoj — COMMENTED** [review]
For me, collabora still doesn't work with this change.

**Comment by szaimen** [comment]
> For me, collabora still doesn't work with this change.

So you are running it behind apache, too?

Or is this happening with other reverse proxies, too?

**Comment by 2020Sanoj** [comment]
> > For me, collabora still doesn't work with this change.
> 
> So you are running it behind apache, too?
> 
> Or is this happening with other reverse proxies, too?

I've stopped my NPM and updated my apache config with this change, started apache server and tested it. So I use the NPM, but have apache2 for testing also installed.
With the NPM it works. But with this apache config not.

**Comment by szaimen** [comment]
> With the NPM it works. But with this apache config not.

Thanks for letting me know!

Yeah, we need to check what we can adjust so that websocket connections for collabora work behind apache, too.

**Comment by szaimen** [comment]
https://httpd.apache.org/docs/current/mod/mod_rewrite.html#rewritecond

**Comment by 2020Sanoj** [comment]
> https://httpd.apache.org/docs/current/mod/mod_rewrite.html#rewritecond
> 
> Check what happens if these get removed:
> 
> https://github.com/nextcloud/all-in-one/blob/56948a81407b6d0c56cbb9b731a4555a9d448e3c/reverse-proxy.md?plain=1#L46-L47

Still same problem

**Comment by 2020Sanoj** [comment]
But Websocket in general works
grafik

**Comment by szaimen** [comment]
Should check and test some things of https://github.com/nextcloud/integration_whiteboard#optionally-make-spacedeck-accessible-via-a-reverse-proxy-in-a-virtual-host

**Comment by szaimen** [comment]
Push notifications do work now with this config but I was unfortunately not abel to make collabora work even after trying for a few hours. I think it does not work because collabora seemingly does not send the upgrade variable nor the connection variable...

**Comment by szaimen** [comment]
merging this since it seems to fix at least this one issue...

**Pull request merged**
