### PR TITLE
Explain how to get the required password

### PR DESCRIPTION
**Pull request by fulldecent**

### CODE REVIEW

**Comment by szaimen** [comment]
Hi, see https://github.com/nextcloud/all-in-one/discussions/1786

**Comment by fulldecent** [comment]
@szaimen Currently the process to install AIO is:

- Install AIO
- There is no password
- Somehow find that GitHub issue

This PR improves it to:

- Install AIO
- Know where to get your password

**Comment by docjyJ** [comment]
The first time you log on, you'll see a page for retrieving your passwords. What do you mean by "there is no password"?

**Comment by fulldecent** [comment]
I completed the process as instructed. And I did not see a page for retrieving a password. I just saw the login page.

**Comment by docjyJ** [comment]
It's the first time the page is loaded. It's possible that refreshing the page twice prevents the password from being displayed.

@szaimen ?

**Comment by szaimen** [comment]
Yes, the password is only shown once...

**Pull request closed without merging**
