### PR TITLE
add check for timezone

### PR DESCRIPTION
**Pull request by szaimen**
Close https://github.com/nextcloud/all-in-one/discussions/3147

### CODE REVIEW

**Comment by Zoey2936** [comment]
maybe also mention, that the timezone should be set inside the aio panel

**Comment by Zoey2936** [comment]
and also is doing exit 1 a good idea?

**Comment by szaimen** [comment]
> maybe also mention, that the timezone should be set inside the aio panel

Good idea!

> and also is doing exit 1 a good idea?

Yes, I don't think many instances have set this. If there should be many reports, we can still remove the exit later.

**Comment by captaindyson** [comment]
This change has caused issues on Unraid. the os adds a TZ to all docker run commands by default, hence preventing the running of the container.
Manualy adding a TZ variable with no value seems to override this, but is not ideal, or at least will require clearly communicating.

**Comment by szaimen** [comment]
Interesting! I guess we will need to fix this then in order to not break all unraid instances.

**Comment by szaimen** [comment]
> This change has caused issues on Unraid. the os adds a TZ to all docker run commands by default, hence preventing the running of the container.

This is now fixed with v7.1.1 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel

**Comment by captaindyson** [comment]
Can confirm this has fixed the issue, warning remains in the logs, but the container starts anyway.

**Pull request merged**
