### PR TITLE
allow _ping docker api to verify service accessible

### PR DESCRIPTION
**Pull request by andrey18106**
Allow `/_ping` api in docker-socket-proxy required for `app_api` to verify docker service connection.

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
Fine by me

**Comment by szaimen** [comment]
@andrey18106 @bigcat88 does my commit look good as well?

**Comment by bigcat88** [comment]
> @andrey18106 @bigcat88 does my commit look good as well?

I like it better the way it was.
I don’t know if Docker will accept "... Privileged " - then after this commit it will pass check, when it should not.

But if Docker rejects such request with `space` at the end after `Privileged` word, then I'm fine.

**Comment by bigcat88** [comment]
> @andrey18106 @bigcat88 does my commit look good as well?

never mind, I deleted my previous comment, misunderstood.
Yeah, I am fine, it looks more strict :)

**Comment by szaimen** [comment]
All right, thanks! :)

**Pull request merged**
