### PR TITLE
manual-install: update readme to use default docker environment file

### PR DESCRIPTION
**Pull request by ManOki**
By using file `.env` directly, the parameter `--env-file my.conf` can be omitted.

### CODE REVIEW

**Review by szaimen — CHANGES_REQUESTED** [review]
Fine by me but you should probably add the file to gitignore: https://github.com/nextcloud/all-in-one/blob/main/.gitignore

**Review by szaimen — COMMENTED** [review]
Thanks! Maxbe it would also be good to add a note for people that are already using it to continue using their my.conf or rename their file to .env?

**Comment by ManOki** [comment]
> Thanks! Maxbe it would also be good to add a note for people that are already using it to continue using their my.conf or rename their file to .env?

What would be the appropriate place for this?

**Comment by szaimen** [comment]
> What would be the appropriate place for this?

I think the readme of manual-install would be a good place :)

**Comment by ManOki** [comment]
I added an instruction to the _How to update?_ section.

**Review by szaimen — APPROVED** [review]
LGTM, thanks! :)

**Pull request merged**
