### PR TITLE
daily backup - allow to disable succesful backup notifications

### PR DESCRIPTION
**Pull request by szaimen**
Close https://github.com/nextcloud/all-in-one/discussions/3485
Close https://github.com/nextcloud/all-in-one/discussions/2180
Close https://github.com/nextcloud/all-in-one/discussions/985
Close https://github.com/nextcloud/all-in-one/discussions/484

### CODE REVIEW

**Comment by chippey5** [comment]
For anyone who is looking how to deactivate the successful backup notifications: 

1. Go to the AIO interface, to the _Backup and restore_ section
2. Press _Click here to reveal all backup options (it also includes an option for automatic updates)_ 
3. Go to the section _Daily backup and automatic updates_. Disable daily backups, if activated.
4. Here's the checkbox introduced to disable notifications: _("Send notifications about successful backups (notifications about unsuccessful backups will always be sent)"). Uncheck to have it disabled when activating daily backups

**Comment by davidSGE** [comment]
@chippey5 
I tried to follow this steps. However there seems to be no button to save the change. I unchecked the option  "Send notifications about successful backups (notifications about unsuccessful backups will always be sent".
No matter if i press "Submit Backup time", "Submit additional backup", "Create backup" or start the containers again, the notification-setting ist always ticked again...
Found no other guide to disable the notifications than yours...

**Comment by chippey5** [comment]
@davidSGE 

Just tested this again (though I haven't waited until my daily automatic backup time yet), but once activated, the checkbox is not visible anymore, so ensure you actually activate automated backups again by pressing "Submit backup time". I realized this wasn't as clear in my previous answer.

**Comment by stargolems** [comment]
> @chippey5 I tried to follow this steps. However there seems to be no button to save the change. I unchecked the option "Send notifications about successful backups (notifications about unsuccessful backups will always be sent)". Afterwards, no matter if I press "Submit Backup time", "Submit additional backup", "Create backup" or start the containers again, the notification-setting ist always ticked again automatically... Found no other guide to disable the notifications than yours...

My AIO 10.0.0 shows the same behaviour: When I uncheck the option ""Send notifications about successful backups ..." and press "Submit Backup time", the setting is always switched on afterwards.

**Comment by chippey5** [comment]
> > @chippey5 I tried to follow this steps. However there seems to be no button to save the change. I unchecked the option "Send notifications about successful backups (notifications about unsuccessful backups will always be sent)". Afterwards, no matter if I press "Submit Backup time", "Submit additional backup", "Create backup" or start the containers again, the notification-setting ist always ticked again automatically... Found no other guide to disable the notifications than yours...
> 
> My AIO 10.0.0 shows the same behaviour: When I uncheck the option ""Send notifications about successful backups ..." and press "Submit Backup time", the setting is always switched on afterwards.

Let's break this down then, this is also tested from the latest (at the time of writing) AIO v10.1.1. For good measure, disable the automatic backups, uncheck the success notifications once more and then submit the automatic backup time. Then:

1. SSH to your VM hosting Nextcloud-AIO
2. Enter the master container: `docker exec -it nextcloud-aio-mastercontainer /bin/bash`
3. Check the backup settings with: `cat /mnt/docker-aio-config/data/daily_backup_time && echo ""`

The latest command should output something like:

```
<your_submitted_backup_start_time>

successNotificationsAreNotEnabled
```

The **3rd** (and last) line ([this is where the master container gets its value from](https://github.com/nextcloud/all-in-one/blob/36888bc56867545cc9524995b28bc90181d4faf9/Containers/mastercontainer/cron.sh#L15-L19)) dictates whether to send success notifications or not. **BUT** only if the 3rd line equals to `successNotificationsAreNotEnabled` it will skip sending notifications, any other value will enable the backup success notifications.

Two things I noticed however:

1. The file is empty if you have automatic backups disabled
2. When disabling automatic backups, the checkbox is automatically marked again by default before submitting it. It's worth noting that as long as you can see the automatic notification section, it means that you have automatic backups disabled. The checkbox status does not seem to be inherited from previous settings as the file is cleared when disabling the backups.

Hope this helps and clears some things out.

**Comment by michield** [comment]
Yes, the UI can do with some work here.  I went through the steps to switch off the notifications, but when reviewing the page, it says 

`Daily backups will be created at 01:00 UTC. A notification about the result of the backup will be sent.`

Even though, as in the post from @chippey5 `successNotificationsAreNotEnabled` is in the config file

**Pull request merged**
