### PR TITLE
do not start container if it is started already

### PR DESCRIPTION
**Pull request by szaimen**
Fix https://github.com/nextcloud/all-in-one/issues/3671

### CODE REVIEW

**Comment by szaimen** [comment]
> Looks good :) I also tested in on my machine and everything worked fine in both scenarios - with DLNA enabled at the first run and when the DLNA is added to the running config. Thanks!

Nice! Thanks for testing :)

**Comment by szaimen** [comment]
This is now released with v7.6.2 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel

**Comment by thanek** [comment]
Tested both installing DLNA on the existing AIO setup and running DLNA together with the fresh AIO installation and all seems to work OK. Thank you! :)

**Comment by szaimen** [comment]
> Tested both installing DLNA on the existing AIO setup and running DLNA together with the fresh AIO installation and all seems to work OK. Thank you! :)

Great to hear! Thanks for testing :)

**Pull request merged**
