### PR TITLE
eturnal - set blacklist_peers

### PR DESCRIPTION
**Pull request by szaimen**
Close https://github.com/nextcloud/all-in-one/discussions/3395

### CODE REVIEW

**Comment by szaimen** [comment]
All right but I think I would keep it for the sake of being more verbose here. Also we use whitelist_peers...

**Comment by sando38** [comment]
> All right but I think I would keep it for the sake of being more verbose here. Also we use whitelist_peers...

Sure. Ask the guys in the discussion threads, if this works during your beta/RC tests. If not, you still may need to add an option to define further whitelisted IP addresses/ranges.

**Comment by szaimen** [comment]
> Sure. Ask the guys in the discussion threads, if this works during your beta/RC tests

I will but I guess I still need for eturnal/eturnal:1.12.0 to get released?

**Comment by sando38** [comment]
> > Sure. Ask the guys in the discussion threads, if this works during your beta/RC tests
> 
> I will but I guess I still need for eturnal/eturnal:1.12.0 to get released?

Definitely. https://github.com/erlang/docker-erlang-otp has not released erlang `26.1`, yet... so we may wait for another one, two days and if not available, we fall back to `26.0.2`, which does not change anything in regard to functionality, security, whatever.

**Comment by szaimen** [comment]
> Definitely. [erlang/docker-erlang-otp](https://github.com/erlang/docker-erlang-otp) has not released erlang `26.1`, yet... so we may wait for another one, two days and if not available, we fall back to `26.0.2`, which does not change anything in regard to functionality, security, whatever.

All right 👍

**Comment by weiss** [comment]
We've now published [eturnal 1.12.0][1], which supports the [`blacklist_peers`][2] thing.

(Greetings from Steglitz!)

[1]: https://eturnal.net/documentation/code/changelog.html#1-12-0-2023-09-28
[2]: https://eturnal.net/documentation/#blacklist_peers

**Comment by szaimen** [comment]
> We've now published [eturnal 1.12.0](https://eturnal.net/documentation/code/changelog.html#1-12-0-2023-09-28), which supports the [`blacklist_peers`](https://eturnal.net/documentation/#blacklist_peers) thing.
> 
> (Greetings from Steglitz!)

Thank you! Greetings back! :)

**Pull request merged**
