### PR TITLE
fix(helm): image repo transformation yielding invalid yaml string syntax

### PR DESCRIPTION
**Pull request by st3iny**
**Did not test the update script! Please verify syntax etc.!**

Helm fails to install the release: `Error: YAML parse error on [...]: error converting YAML to JSON: yaml: line 42: did not find expected key`

### Broken

```yaml
image: "{{ .Values.IMAGE_MIRROR_PREFIX }}{{ .Values.NEXTCLOUD_IMAGE_ORG }}"/foo-bar:baz
```

### Working

```yaml
image: "{{ .Values.IMAGE_MIRROR_PREFIX }}{{ .Values.NEXTCLOUD_IMAGE_ORG }}/foo-bar:baz"
```

### CODE REVIEW

**Comment by szaimen** [comment]
@st3iny do you know if there is some helm linting workflow available somewhere?

**Comment by st3iny** [comment]
You could run `helm lint` :smile: 

```
$ helm lint
==> Linting .
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/nextcloud-enterprise-database-deployment.yaml: unable to parse YAML: error converting YAML to JSON: yaml: line 66: did not find expected key
[ERROR] templates/nextcloud-enterprise-imaginary-deployment.yaml: unable to parse YAML: error converting YAML to JSON: yaml: line 31: did not find expected key
[ERROR] templates/nextcloud-enterprise-notify-push-deployment.yaml: unable to parse YAML: error converting YAML to JSON: yaml: line 54: did not find expected key
[ERROR] templates/nextcloud-enterprise-redis-deployment.yaml: unable to parse YAML: error converting YAML to JSON: yaml: line 43: did not find expected key

Error: 1 chart(s) linted, 1 chart(s) failed
```

**Comment by st3iny** [comment]
We actually have such a workflow but it doesn't seem to run anymore. I'll investigate.

**Comment by st3iny** [comment]
It was disabled manually it seems.

**Comment by szaimen** [comment]
Lets for now add it to the helm release workflow: https://github.com/nextcloud/all-in-one/pull/4450

**Pull request merged**
