### PR TITLE
Add apache container reachability check and retry mechanism to run-exec-commands.sh

### LINKED ISSUE #5722: Onlyoffice container not working propertly after restart.
### Steps to reproduce
1. Reboot the machine without stopping all the containers on the Mastercontainer.
2. Wait until all the containers are up.

### Expected behavior 

Nextcloud should show all the document options in the "New" button to create files when Onlyoffice container is enabled.

### Actual behavior 

Can't open office file documents.

Document options and file associations in Onlyoffice app settings are missing until you stop the containers and start it again.

#### Host OS 

Debian 12.8 Bookworm x64 with OpenMediaVault webui.

#### Output of `sudo docker info`

```

Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
Server:
 Containers: 19
  Running: 14
  Paused: 0
  Stopped: 5
 Images: 21
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 88bf19b2105c8b17560993bee28a01ddc2f97182
 runc version: v1.2.2-0-g7cb3632
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.0-28-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.781GiB
 Name: bodega
 ID: b1008ccb-6598-42a1-b66e-d222eeff3754
 Docker Root Dir: /srv/dev-disk-by-uuid-5779b390-7ca4-46ca-aff0-490ab9220a67/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

```

#### Docker run command or docker-compose file that you used

```
services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    restart: always
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed as otherwise AIO will not work correctly
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed as otherwise the built-in backup solution will not work
      - /var/run/docker.sock:/var/run/docker.sock:ro # May be changed on macOS, Windows or docker rootless. See the applicable documentation. If adjusting, don't forget to also set 'WATCHTOWER_DOCKER_SOCKET_PATH'!
    network_mode: bridge # add to the same network as docker run would do
    ports:
      # - 80:80 # Can be removed when running behind a web server or reverse proxy (like Apache, Nginx, Caddy, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - 8080:8080
      # - 8443:8443 # Can be removed when running behind a web server or reverse proxy (like Apache, Nginx, Caddy, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
    environment: # Is needed when using any of the options below
      # AIO_DISABLE_BACKUP_SECTION: false # Setting this to true allows to hide the backup section in the AIO interface. See https://github.com/nextcloud/all-in-one#how-to-disable-the-backup-section
      AIO_COMMUNITY_CONTAINERS: memories # With this variable, you can add community containers very easily. See https://github.com/nextcloud/all-in-one/tree/main/community-containers#community-containers
      APACHE_PORT: 11000 # Is needed when running behind a web server or reverse proxy (like Apache, Nginx, Caddy, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      APACHE_IP_BINDING: 0.0.0.0 # Should be set when running behind a web server or reverse proxy (like Apache, Nginx, Caddy, Cloudflare Tunnel and else) that is running on the same host. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      # BORG_RETENTION_POLICY: --keep-within=7d --keep-weekly=4 --keep-monthly=6 # Allows to adjust borgs retention policy. See https://github.com/nextcloud/all-in-one#how-to-adjust-borgs-retention-policy
      # COLLABORA_SECCOMP_DISABLED: false # Setting this to true allows to disable Collabora's Seccomp feature. See https://github.com/nextcloud/all-in-one#how-to-disable-collaboras-seccomp-feature
      NEXTCLOUD_DATADIR: ${PATH_TO_NCDATA} # Allows to set the host directory for Nextcloud's datadir. ⚠️⚠️⚠️ Warning: do not set or adjust this value after the initial Nextcloud installation is done! See https://github.com/nextcloud/all-in-one#how-to-change-the-default-location-of-nextclouds-datadir
      NEXTCLOUD_MOUNT: /srv/ # Allows the Nextcloud container to access the chosen directory on the host. See https://github.com/nextcloud/all-in-one#how-to-allow-the-nextcloud-container-to-access-directories-on-the-host
      NEXTCLOUD_UPLOAD_LIMIT: 150G # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-upload-limit-for-nextcloud
      NEXTCLOUD_MAX_TIME: 86400 # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-max-execution-time-for-nextcloud
      NEXTCLOUD_MEMORY_LIMIT: 1024M # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-php-memory-limit-for-nextcloud
      # NEXTCLOUD_TRUSTED_CACERTS_DIR: /path/to/my/cacerts # CA certificates in this directory will be trusted by the OS of the nexcloud container (Useful e.g. for LDAPS) See See https://github.com/nextcloud/all-in-one#how-to-trust-user-defined-certification-authorities-ca
      # NEXTCLOUD_STARTUP_APPS: deck twofactor_totp tasks calendar contacts notes # Allows to modify the Nextcloud apps that are installed on starting AIO the first time. See https://github.com/nextcloud/all-in-one#how-to-change-the-nextcloud-apps-that-are-installed-on-the-first-startup
      NEXTCLOUD_ADDITIONAL_APKS: nano vim imagemagick # This allows to add additional packages to the Nextcloud container permanently. Default is imagemagick but can be overwritten by modifying this value. See https://github.com/nextcloud/all-in-one#how-to-add-os-packages-permanently-to-the-nextcloud-container
      # NEXTCLOUD_ADDITIONAL_PHP_EXTENSIONS: imagick # This allows to add additional php extensions to the Nextcloud container permanently. Default is imagick but can be overwritten by modifying this value. See https://github.com/nextcloud/all-in-one#how-to-add-php-extensions-permanently-to-the-nextcloud-container
      NEXTCLOUD_ENABLE_DRI_DEVICE: true # This allows to enable the /dev/dri device in the Nextcloud container. ⚠️⚠️⚠️ Warning: this only works if the '/dev/dri' device is present on the host! If it should not exist on your host, don't set this to true as otherwise the Nextcloud container will fail to start! See https://github.com/nextcloud/all-in-one#how-to-enable-hardware-transcoding-for-nextcloud
      # NEXTCLOUD_KEEP_DISABLED_APPS: false # Setting this to true will keep Nextcloud apps that are disabled in the AIO interface and not uninstall them if they should be installed. See https://github.com/nextcloud/all-in-one#how-to-keep-disabled-apps
      # TALK_PORT: 3478 # This allows to adjust the port that the talk container is using. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-talk-port
      # WATCHTOWER_DOCKER_SOCKET_PATH: /var/run/docker.sock # Needs to be specified if the docker socket on the host is not located in the default '/var/run/docker.sock'. Otherwise mastercontainer updates will fail. For macos it needs to be '/var/run/docker.sock'
    # security_opt: ["label:disable"] # Is needed when using SELinux

  # # Optional: Caddy reverse proxy. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
  # # You can find further examples here: https://github.com/nextcloud/all-in-one/discussions/588
  # caddy:
  #   image: caddy:alpine
  #   restart: always
  #   container_name: caddy
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile
  #     - ./certs:/certs
  #     - ./config:/config
  #     - ./data:/data
  #     - ./sites:/srv
  #   network_mode: "host"

volumes: # If you want to store the data on a different drive, see https://github.com/nextcloud/all-in-one#how-to-store-the-filesinstallation-on-a-separate-drive
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # 

```

#### Other valuable info 

Onlyoffice container log:

```

2024-12-07T03:06:18.688902718Z Generating WOPI private key...Done
2024-12-07T03:06:18.840115743Z Generating WOPI public key...Done
2024-12-07T03:06:22.794779087Z  * Starting PostgreSQL 14 database server
2024-12-07T03:06:26.889128222Z    ...done.
2024-12-07T03:06:26.926879404Z  * Starting RabbitMQ Messaging Server rabbitmq-server
2024-12-07T03:07:01.194732332Z    ...done.
2024-12-07T03:07:01.588155556Z psql:/var/www/onlyoffice/documentserver/server/schema/postgresql/removetbl.sql:4: NOTICE:  table "doc_callbacks" does not exist, skipping
2024-12-07T03:07:01.869568449Z psql:/var/www/onlyoffice/documentserver/server/schema/postgresql/removetbl.sql:9: NOTICE:  function merge_db(pg_catalog.varchar,int2,int8,pg_catalog.timestamp,pg_catalog.varchar,int8,int8) does not exist, skipping
2024-12-07T03:07:01.869849780Z psql:/var/www/onlyoffice/documentserver/server/schema/postgresql/removetbl.sql:10: NOTICE:  function merge_db(pg_catalog.varchar,int2,int4,pg_catalog.timestamp,pg_catalog.varchar,int4,int4) does not exist, skipping
2024-12-07T03:07:01.870086610Z psql:/var/www/onlyoffice/documentserver/server/schema/postgresql/removetbl.sql:11: NOTICE:  function merge_db(pg_catalog.varchar,int2,int4,pg_catalog.timestamp,int4,int4,text,text) does not exist, skipping
2024-12-07T03:07:07.225618337Z Starting supervisor: supervisord.
2024-12-07T03:07:07.266186899Z  * Starting periodic command scheduler cron
2024-12-07T03:07:07.306244630Z    ...done.
2024-12-07T03:07:07.467040978Z  * Starting nginx nginx
2024-12-07T03:07:07.547074284Z    ...done.
2024-12-07T03:08:21.569852993Z Generating AllFonts.js, please wait...Done
2024-12-07T03:09:13.126136180Z Generating presentation themes, please wait...Done
2024-12-07T03:09:18.143459830Z Generating js caches, please wait...Done
2024-12-07T03:09:20.388643698Z /usr/bin/documentserver-generate-allfonts.sh: 65: /var/www/onlyoffice/documentserver/sdkjs/slide/themes/themes.js.gz: not found
2024-12-07T03:09:23.979998016Z ds:docservice: stopped
2024-12-07T03:09:23.980045349Z ds:docservice: started
2024-12-07T03:09:25.464378774Z ds:converter: stopped
2024-12-07T03:09:25.464431417Z ds:converter: started
2024-12-07T03:09:28.204328030Z  * Reloading nginx configuration nginx
2024-12-07T03:09:36.634572256Z    ...done.
2024-12-07T03:10:26.280115233Z Installing plugins, please wait...Done
2024-12-07T03:13:23.597683215Z  * Reloading nginx configuration nginx
2024-12-07T03:13:26.589026276Z    ...done.
2024-12-07T03:13:26.607657914Z 
2024-12-07T03:13:26.841801934Z ==> /var/log/onlyoffice/documentserver/converter/err.log <==
2024-12-07T03:13:26.841869940Z 
2024-12-07T03:13:26.841879241Z ==> /var/log/onlyoffice/documentserver/converter/out.log <==
2024-12-07T03:13:26.841888169Z [2024-12-07T03:07:37.741] [WARN] [localhost] [docId] [userId] nodeJS - num of CPUs: 4; availableParallelism: undefined
2024-12-07T03:13:26.841929366Z [2024-12-07T03:07:37.746] [WARN] [localhost] [docId] [userId] nodeJS - update cluster with 1 workers
2024-12-07T03:13:26.841939312Z [2024-12-07T03:07:37.876] [WARN] [localhost] [docId] [userId] nodeJS - worker 779 started.
2024-12-07T03:13:26.841947829Z [2024-12-07T03:07:37.878] [WARN] [localhost] [docId] [userId] nodeJS - num of CPUs: 4; availableParallelism: undefined
2024-12-07T03:13:26.841956187Z [2024-12-07T03:07:37.879] [WARN] [localhost] [docId] [userId] nodeJS - update cluster with 1 workers
2024-12-07T03:13:26.841964353Z [2024-12-07T03:09:39.717] [WARN] [localhost] [docId] [userId] nodeJS - num of CPUs: 4; availableParallelism: undefined
2024-12-07T03:13:26.841972742Z [2024-12-07T03:09:39.722] [WARN] [localhost] [docId] [userId] nodeJS - update cluster with 1 workers
2024-12-07T03:13:26.841980854Z [2024-12-07T03:09:39.746] [WARN] [localhost] [docId] [userId] nodeJS - worker 1044 started.
2024-12-07T03:13:26.841989263Z [2024-12-07T03:09:39.748] [WARN] [localhost] [docId] [userId] nodeJS - num of CPUs: 4; availableParallelism: undefined
2024-12-07T03:13:26.841997693Z [2024-12-07T03:09:39.749] [WARN] [localhost] [docId] [userId] nodeJS - update cluster with 1 workers
2024-12-07T03:13:26.842005962Z 
2024-12-07T03:13:26.842013534Z ==> /var/log/onlyoffice/documentserver/docservice/err.log <==
2024-12-07T03:13:26.842021862Z 
2024-12-07T03:13:26.842029782Z ==> /var/log/onlyoffice/documentserver/docservice/out.log <==
2024-12-07T03:13:26.842037988Z [2024-12-07T03:08:09.133] [WARN] [localhost] [docId] [userId] nodeJS - Express server starting...
2024-12-07T03:13:26.842046340Z [2024-12-07T03:08:09.136] [WARN] [localhost] [docId] [userId] nodeJS - Failed to subscribe to plugin folder updates. When changing the list of plugins, you must restart the server. https://nodejs.org/docs/latest/api/fs.html#fs_availability
2024-12-07T03:13:26.842057062Z [2024-12-07T03:08:09.610] [WARN] [localhost] [docId] [userId] nodeJS - notifyLicenseExpiration(): expiration date is not defined
2024-12-07T03:13:26.842065438Z [2024-12-07T03:08:09.611] [WARN] [localhost] [docId] [userId] nodeJS - notifyLicenseExpiration(): expiration date is not defined
2024-12-07T03:13:26.842075912Z [2024-12-07T03:08:12.371] [WARN] [localhost] [docId] [userId] nodeJS - Express server listening on port 8000 in production-linux mode. Version: 8.2.0. Build: 143
2024-12-07T03:13:26.842084969Z [2024-12-07T03:09:54.888] [WARN] [localhost] [docId] [userId] nodeJS - Express server starting...
2024-12-07T03:13:26.842093228Z [2024-12-07T03:09:54.891] [WARN] [localhost] [docId] [userId] nodeJS - Failed to subscribe to plugin folder updates. When changing the list of plugins, you must restart the server. https://nodejs.org/docs/latest/api/fs.html#fs_availability
2024-12-07T03:13:26.842102468Z [2024-12-07T03:09:54.942] [WARN] [localhost] [docId] [userId] nodeJS - notifyLicenseExpiration(): expiration date is not defined
2024-12-07T03:13:26.842110998Z [2024-12-07T03:09:54.943] [WARN] [localhost] [docId] [userId] nodeJS - notifyLicenseExpiration(): expiration date is not defined
2024-12-07T03:13:26.842119626Z [2024-12-07T03:09:55.448] [WARN] [localhost] [docId] [userId] nodeJS - Express server listening on port 8000 in production-linux mode. Version: 8.2.0. Build: 143
2024-12-07T03:13:26.842136307Z 
2024-12-07T03:13:26.842145097Z ==> /var/log/onlyoffice/documentserver/nginx.error.log <==


```

Screenshots:

### PR DESCRIPTION
**Pull request by JMarcosHP**
Closes #5722

### CODE REVIEW

**Comment by szaimen** [comment]
Hey, thanks a lot for the PR! :)

However I would prefer a solution where we wait for the apache container to be available and then run the command directly.
Do you think you can implement this?

**Comment by JMarcosHP** [comment]
> Hey, thanks a lot for the PR! :)
> 
> However I would prefer a solution where we wait for the apache container to be available and then run the command directly. Do you think you can implement this?

Sure! We can do this, but we need to parse 2 environment variables to the nextcloud container, `$APACHE_HOST` and `$APACHE_PORT` to get it working instead of `$NC_DOMAIN`

**Comment by JMarcosHP** [comment]
Currently we only have $APACHE_PORT inside the container. I don't know where the nextcloud container get these values or how to add the $APACHE_HOST env variable to get it working.

```
1ec2eea84ebf:/var/www/html# printenv | grep APACHE
APACHE_PORT=11000
```

**Comment by JMarcosHP** [comment]
Now if the apache container is not running or is not ready the script will wait until is ready.

Captura desde 2024-12-17 11-18-18

**Pull request merged**
