### PR TITLE
add a details tag to note down more included features

### PR DESCRIPTION
**Pull request by szaimen**

### CODE REVIEW

**Comment by Zoey2936** [comment]
> Ready to be used behind [Cloudflare Tunnel](https://github.com/nextcloud/all-in-one#how-to-run-nextcloud-behind-a-cloudflare-tunnel)

I think not...

**Comment by szaimen** [comment]
> I think not...

Ah you mean due to the talk problems?

Donyou have further remarkd or additions? :)

**Comment by Zoey2936** [comment]
1. yes and the many other problems
2. no

**Comment by szaimen** [comment]
> * yes and the many other problems
> * no

Thanks for the feedback! I adjusted the wording and will merge this when everything is green :)

**Pull request merged**
