### PR TITLE
document how to reset the instance properly

### PR DESCRIPTION
**Pull request by szaimen**
Close https://github.com/nextcloud/all-in-one/issues/665

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by szaimen** [comment]
@Joly0 does this look good to you? :)

**Comment by Joly0** [comment]
In my opinion the commands should be adjusted so not all containers and images not running get deleted.

Here is an example command, that might work (not tested)

Docker container prune --filter name=nextcloud_aio_*

And the volume equivalent should be used, though i havent tested this command.

Otherwise these commands should work

docker rm -f $(docker ps -a -q --filter name=nextcloud_aio_*)

docker volume rm $(docker volume ls -q --filter name=nextcloud_aio_*)


I could test these later today, if needed.

**Comment by szaimen** [comment]
Thanks, good suggestion! I'll adjust the documentation accordingly!

**Comment by szaimen** [comment]
@Joly0 does this look good to you now? :)

**Comment by Joly0** [comment]
As far as i know, there is the possibility to filter for names though i would have to test that.
So if you could wait a bit longer, than i would test that and try to figure out a way how this could work.

**Comment by szaimen** [comment]
> As far as i know, there is the possibility to filter for names though i would have to test that. So if you could wait a bit longer, than i would test that and try to figure out a way how this could work.

All right, I'll wait then until you report back if you found a solution 👍 thanks for investigating! :)

**Comment by Joly0** [comment]
I have found the correct command to remove the containers and their volumes (though the images are not getting deleted)

docker rm -v $(docker ps -a -q --filter name=nextcloud)

Would be great, if someone could test and verify that command. If i find a command for deleting the images aswell, then i will add it here

**Comment by szaimen** [comment]
@Joly0 thanks for investigating but I honestly would not use the command substitution here because it will not work on all supported platforms so I adjusted the commands to show which things will be removed before executing the specific commands. Is that fine for you, too?

**Comment by Joly0** [comment]
Alright, i didnt thought about every usecase and you are right, some platforms dont or might not support this way. So if it is well documented, what the commands do and what to take care of, i am fine with it

**Comment by szaimen** [comment]
All right! Thanks for your review! Merging then :)

**Pull request merged**
