### PR TITLE
talk-recording - allow to set hpb_domain and nc_domain independently

### PR DESCRIPTION
**Pull request by szaimen**
Address https://github.com/nextcloud/vm/issues/2522#issuecomment-1643979804

### CODE REVIEW

**Comment by enoch85** [comment]
Thank you very much!

**Comment by enoch85** [comment]
@szaimen I think it looks good. What are we waiting for?

**Review by enoch85 — APPROVED** [review]

**Comment by szaimen** [comment]
> @szaimen I think it looks good. What are we waiting for?

Waiting for the next release to be published which is planned for this friday.

**Comment by enoch85** [comment]
Woha!

**Comment by szaimen** [comment]
This is now released with v7.0.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel

**Pull request merged**
