### PR TITLE
allow to exclude previews from restore upon instance restore

### PR DESCRIPTION
**Pull request by szaimen**
Close https://github.com/nextcloud/all-in-one/issues/5451

### CODE REVIEW

**Comment by szaimen** [comment]
@timdiels can you please have a look how to achieve the same for remote backups?
Thanks in advance! :)

**Comment by timdiels** [comment]
@szaimen I'll have a look Sunday. Do you want me to add it to this PR?

**Comment by szaimen** [comment]
> @szaimen I'll have a look Sunday. 

Thanks!

> Do you want me to add it to this PR?

Yes please :)

**Comment by timdiels** [comment]
Tested the remote case with and without preview locally. Works for me

**Review by timdiels — APPROVED** [review]
Your changes LGTM but someone should still have a look at mine

**Pull request merged**
