### PR TITLE
RP docs - add Citrix ADC VPX / Citrix Netscaler 

### PR DESCRIPTION
**Pull request by esmith443**
Added guide for Citrix ADC VPX / Citrix Netscaler reverse proxy. This is my first pull so I am sorry if I made any mistakes. Love AIO thanks :)

### CODE REVIEW

**Comment by szaimen** [comment]
Hi @esmith443 thanks a lot for your PR and sorry for coming back so late to you!

Unfortunately after having a second look at this, it looks a bit too much to put it directly into the reverse proxy documentation. 

Would it be okay for you to create post in the wiki section here: https://github.com/nextcloud/all-in-one/discussions/new?category=wiki and we simply link to that from the RP docs?

**Comment by esmith443** [comment]
Sure, I will do that now.

Thank you

**Comment by esmith443** [comment]
https://github.com/nextcloud/all-in-one/discussions/2452

**Comment by esmith443** [comment]
Created a new commit with just a link to the guide.

**Review by szaimen — APPROVED** [review]
Thank you very much! Looks good to me now! :)

**Pull request merged**
