### PR TITLE
document multiarch containers

### PR DESCRIPTION
**Pull request by szaimen**

### CODE REVIEW

**Comment by Zoey2936** [comment]
Maybe we should also somewhere mention that AIO only supports arm64/aarch64/armv8 and amd64/x86/x86_64?
32Bit (armv7) Raspberry Pi OS is still often used and still preselected by the Raspberry Pi imager

**Comment by szaimen** [comment]
> Maybe we should also somewhere mention that AIO only supports arm64/aarch64/armv8 and amd64/x86/x86_64?

Sounds good. Would you mind creating a PR? :)

**Comment by Zoey2936** [comment]
I'm not sure where a good place is, to mention this inside the readme, I thought about the first line
And also how to call arm64/aarch64/armv8 and amd64/x86/x86_64 exactly because of this many names

**Comment by szaimen** [comment]
Maybe just add it somewhere in the FAQ section? I would not like to put it into the instructions...

**Comment by szaimen** [comment]
Thanks!

**Pull request merged**
