### PR TITLE
manual-install - enable ipv6 by default

### PR DESCRIPTION
**Pull request by szaimen**

### CODE REVIEW

**Comment by Zoey2936** [comment]
does this not crash instances with disabled ipv6?

**Comment by szaimen** [comment]
> does this not crash instances with disabled ipv6?

True, but people need to update manually anyway so they hopefully catch the issue directly and disable ipv6 if they should not have it enabled and just comment this section. 

Additionally ipv6 should nowadays get enabled by default if you ask me...

**Comment by Zoey2936** [comment]
maybe it should at least be somewhere (release notes, manual-install-readme and/or somewhere else) be mentioned?

**Comment by szaimen** [comment]
> maybe it should at least be somewhere (release notes, manual-install-readme and/or somewhere else) be mentioned?

Manual-install readme sounds fine. Let me create a PR for that.

**Comment by szaimen** [comment]
Done with https://github.com/nextcloud/all-in-one/commit/0fdcba047d0a95f749551b0bb88fba280f9562d5

**Pull request merged**
