### PR TITLE
add a note on docker-rootless regarding permissions outside the conta…

### PR DESCRIPTION
**Pull request by szaimen**
…iners

Close https://github.com/nextcloud/all-in-one/issues/823

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by szaimen** [comment]
@Kirk1984 does this look good to you?

**Comment by Kirk1984** [comment]
I don't think that will work.
In my test the user pi is 1000:1000 and the Folder the rootless docker should use is pi:pi. It didn't work. It only worked when i setup Nextcloud All in One with a volume and copied the value that volume had (1000032:1000032) onto the Folder i want to Bind. Only then it worked. But "systemctl --user status docker" shows only group 1000 for cgroup and containerd.

"ps -u pi" shows that the user pi runs docker (dockerd, containerd, etc). The same user that created the folder that should be used as a bind volume.

**Comment by szaimen** [comment]
Okay, so the folders outside the containers do not created with the user that is running the docker daemon?

**Comment by Kirk1984** [comment]
> Okay, so the folders outside the containers do not created with the user that is running the docker daemon?

No, the volume was 100032:100032. Which seems to be normal (what i found googling). Looks like the values are always over 100000. 

 grep ^$(whoami): /etc/subuid shows also 100000 as the first value.

**Comment by szaimen** [comment]
Hm... then this is maybe really a bug?

Or could `100032:100032` be applied to make it work?

**Comment by Kirk1984** [comment]
When i'm i will check if maybe values over100000 work in general. My older system doesn't use 32 but 999.

**Pull request merged**
