### PR TITLE
Update update-yaml.sh

### PR DESCRIPTION
**Pull request by Zoey2936**
see: https://github.com/nextcloud/all-in-one/discussions/3085#discussioncomment-6649658

Close https://github.com/nextcloud/all-in-one/issues/3088
Close https://github.com/nextcloud/all-in-one/issues/3085

### CODE REVIEW

**Comment by szaimen** [comment]
Thanks @Zoey2936 ! Unfortunately it does not seem to work yet: https://github.com/nextcloud/all-in-one/actions/runs/5800587407/job/15723004875

**Comment by Zoey2936** [comment]
> Thanks @Zoey2936 ! Unfortunately it does not seem to work yet: https://github.com/nextcloud/all-in-one/actions/runs/5800587407/job/15723004875

should be fixed

**Comment by szaimen** [comment]
Seems tow work, thanks! :)

https://github.com/nextcloud/all-in-one/pull/3113/files

**Comment by szaimen** [comment]
@GuillaumeHullin does this look good to you? :)

**Review by szaimen — APPROVED** [review]
LGTM, thanks! :)

**Comment by GuillaumeHullin** [comment]
Hi again @szaimen, I talk too fast... I didn't notice the changes between my PR yaml and this one...
```yaml
# Incorrect:
      - nextcloud-aio-onlyoffice:
           condition: service_started
           required: false

# Correct
      nextcloud-aio-onlyoffice:
         condition: service_started
         required: false
```

The added `-` generate the error `services.nextcloud-aio-apache.depends_on must be a mapping`

I'm not 100% sure how to test modification of update-yaml.sh script.

**Pull request merged**
