### PR TITLE
update update-yaml.sh follow-up 

### PR DESCRIPTION
**Pull request by Zoey2936**

### CODE REVIEW

**Comment by Zoey2936** [comment]
not sure if it works, then compose file has linebreaks I didn't expected https://github.com/nextcloud/all-in-one/pull/3119

**Comment by szaimen** [comment]
This is how it would look like: https://github.com/nextcloud/all-in-one/pull/3120/files. Is the linebreak intended?

**Comment by Zoey2936** [comment]
> This is how it would look like: https://github.com/nextcloud/all-in-one/pull/3120/files. Is the linebreak intended?

no they are not, but no Idea why they exist

**Comment by szaimen** [comment]
> no they are not, but no Idea why they exist

All right, shall we try to find a workaround for this or is it fine?

**Comment by szaimen** [comment]
Found the solution.

**Review by szaimen — APPROVED** [review]

**Pull request merged**
