### PR TITLE
run all command in one RUN step

### PR DESCRIPTION
**Pull request by Zoey2936**

### CODE REVIEW

**Comment by Zoey2936** [comment]
> Wow, thanks a lot for this big PR @Zoey2936! :)
> 
> I think it would make sense though to split this PR into one PR for each container since it makes reviewing much simpler and easier to merge the changes. Would you be up for this? :)

I will try to split it today or tomorrow.

**Comment by szaimen** [comment]
> I will try to split it today or tomorrow.

Thanks a lot! :)

**Comment by Zoey2936** [comment]
done

**Comment by szaimen** [comment]
Thanks a lot! 🤗

**Comment by Zoey2936** [comment]
Not sure if I overwrotte some last changes in the dockerfiles, since I just copied them, and I'm now not sure if the dockerfile-optimze branch was uptodate

**Comment by Zoey2936** [comment]
> Not sure if I overwrotte some last changes in the dockerfiles, since I just copied them, and I'm now not sure if the dockerfile-optimze branch was uptodate

it reverted the elastic version and golang version

**Pull request closed without merging**
