### PR TITLE
follow-links should be follow-link

### PR DESCRIPTION
**Pull request by tyleraharrison**
`--get-links` -> `--get-link`

Signed-off-by: tyleraharrison <tyleraharrison@gmail.com>

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
Thanks, LGTM!

**Comment by tyleraharrison** [comment]
@szaimen I know this has been merged, will probably open another issue, I noticed this `docker cp` command actually puts the data folder inside the data folder. Maybe it needs to be a data/* or something along those lines. I had to manually move all of the data folder to `..` to fix it.

**Comment by szaimen** [comment]
Oh that is unfortune. Can you create another PR to document the fix of the problem?

**Comment by tyleraharrison** [comment]
> Oh that is unfortune. Can you create another PR to document the fix of the problem?

Mentioned it here https://github.com/nextcloud/all-in-one/issues/1842. I don't know if the fix is just adding a `*` or what, I can try it later

**Pull request merged**
