### PR TITLE
Add hint about Cloudflare Rocket Loader and Rename Cloudflare Argo Tu…

### PR DESCRIPTION
**Pull request by szaimen**
…nnel to Cloudflare Tunnel

Close https://github.com/nextcloud/all-in-one/discussions/1677

Signed-off-by: Simon L <szaimen@e.mail.de>

### CODE REVIEW

**Comment by szaimen** [comment]
@itsMaxio does this look good to you? :)

**Comment by Zoey2936** [comment]
I think the rocket loader part should be also generally mentioned somewhere, since AIO can also be running behind Cloudflare without using tunnels

**Review by itsMaxio — APPROVED** [review]
Yeah looks good thanks for the quick reply :)

**Comment by szaimen** [comment]
> I think the rocket loader part should be also generally mentioned somewhere, since AIO can also be running behind Cloudflare without using tunnels

Interesting! @Zoey2936 , can you create a new issue for that or maybe create a PR that mentions this directly? Thanks! :)

**Comment by szaimen** [comment]
And thankks for the approval @itsMaxio ! :)

**Pull request merged**
