### PR TITLE
add custom ipv6 docs

### PR DESCRIPTION
**Pull request by szaimen**

### CODE REVIEW

**Review by Zoey2936 — APPROVED** [review]
looks similar to the mailcow deamon.json, so should work

**Comment by szaimen** [comment]
Thanks! :)

**Comment by szaimen** [comment]
> looks similar to the mailcow deamon.json

Apparently it is pretty hidden in their shell script: https://github.com/mailcow/mailcow-dockerized/blob/428b917579f9f12236fbf1655edbbf5da300969f/update.sh#L110-L115

**Comment by Zoey2936** [comment]
yes, https://github.com/mailcow/mailcow-dockerized/blob/428b917579f9f12236fbf1655edbbf5da300969f/update.sh#L91

**Pull request merged**
