### PR TITLE
fix daily backup running into conflict with elasticsearch

### PR DESCRIPTION
**Pull request by szaimen**
Fix https://github.com/nextcloud/all-in-one/discussions/1875

Signed-off-by: Simon L <szaimen@e.mail.de>

### CODE REVIEW

**Comment by szaimen** [comment]
@Zoey2936 do you maybe have a good idea how to fix https://github.com/nextcloud/all-in-one/discussions/1875 in a more general way?

**Comment by Zoey2936** [comment]
At the moment not

**Comment by szaimen** [comment]
> At the moment not

yeah, same for me unfortunately...

**Comment by szaimen** [comment]
WDYT about adding a tcp connection to the backup container that other container listen to?

E.g. 
```
while nc -z "$BACKUP_HOST" "$BACKUP_HOST" &>/dev/null; then
    echo "waiting for backup container to stop..."
fi
```

**Pull request merged**
