### PR TITLE
add docker healthchecks to the docker images

### PR DESCRIPTION
**Pull request by Zoey2936**
Signed-off-by: Zoey <zoey@z0ey.de>

See #1027

### CODE REVIEW

**Comment by szaimen** [comment]
@Zoey2936 just tested and it seems like nextcloud-aio-apache is reported as unhealthy:
image

Also running `curl -skfI localhost:8000 && curl -skfI localhost:$APACHE_PORT; echo $? inside the container returns 22...

Can you please have a look?

**Comment by Zoey2936** [comment]
grafik
For me, it works, but I will check

**Comment by Zoey2936** [comment]
What is your output if you run this?

> @Zoey2936 just tested and it seems like nextcloud-aio-apache is reported as unhealthy: image
> 
> Also running `curl -skfI localhost:8000 && curl -skfI localhost:$APACHE_PORT; echo $?` inside the container returns 22...
> 
> Can you please have a look?

**Comment by szaimen** [comment]
```
curl -skfI localhost:8000 && curl -skfI localhost:$APACHE_PORT; echo $?
HTTP/1.1 302 Found
Date: Thu, 25 Aug 2022 14:10:19 GMT
Server: Apache/2.4.54 (Debian)
X-Powered-By: PHP/8.0.22
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Content-Security-Policy: default-src 'self'; script-src 'self' 'nonce-a1B4TGhpcG9NSkkySTRmdStaMENYL1dQd1dSVmVQTmQ5cGFyNmJ3UVAyMD06NEtrKy9FMDZXdmRHUk1QY2lQTXdLNUhHaXd3dkhNTXltL252aDlRcFdnND0='; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *; object-src 'none'; base-uri 'self';
Set-Cookie: oc_sessionPassphrase=gYnFh%2FBdOJuXYtpbtQlxFWx8QWCUQNFPr3kY0mpjVYgXMtfYmpx%2FPeP%2BcRCFAkCSLw9DR82QZDUfmgNqcv%2BVSpW925byxs47g2cnpCjgqR2Q1QRVg3ku1tI8r7MnM%2BNG; path=/; secure; HttpOnly; SameSite=Lax
Set-Cookie: ocdph6m977ya=0221e9d0ef54b87a1be53d8bf62cfc47; path=/; secure; HttpOnly; SameSite=Lax
Set-Cookie: __Host-nc_sameSiteCookielax=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax
Set-Cookie: __Host-nc_sameSiteCookiestrict=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict
Referrer-Policy: no-referrer
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Robots-Tag: none
X-XSS-Protection: 1; mode=block
Location: https://domain.com/login
Content-Type: text/html; charset=UTF-8

22
```

**Comment by szaimen** [comment]
Ah, I know why. it is not running behind a reverse proxy. So Caddy will only listen on the provided domain.

**Comment by Zoey2936** [comment]
> Ah, I know why. it is not running behind a reverse proxy. So Caddy will only listen on the provided domain.

And what now?

**Comment by szaimen** [comment]
This works for me: `curl -skfI https://$NC_DOMAIN:$APACHE_PORT`

**Comment by szaimen** [comment]
Maybe add some logic into the healthcheck?

**Comment by szaimen** [comment]
Can you run echo $NC_DOMAIN inside the apache container? What does it return?

**Comment by Zoey2936** [comment]
It returns my domain, but my $APACHE_PORT is 11000, but `https://$NC_DOMAIN:$APACHE_PORT` will not work, since port 11000 is not exposed and only aviable over localhost

**Comment by szaimen** [comment]
Hm... that is then really not so easy to solve...

**Comment by Zoey2936** [comment]
The healthcheck can also be a script that is executed, maybe this helps

**Comment by szaimen** [comment]
I think wee need to check as well if the apache_port is 443 and if yes do the check like it works for me ans if not do it like you proposed...

**Comment by Zoey2936** [comment]
Could you have a look at #1060

**Pull request merged**
