### PR TITLE
add documentation for docker rootless

### PR DESCRIPTION
**Pull request by szaimen**
Close https://github.com/nextcloud/all-in-one/issues/558

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by Kirk1984** [comment]
Wouldn't it be better to leave to steps to get docker rootless up to the documentation for docker? Under Ubuntu the rootless stuff can be installed via repository for example.

**Comment by szaimen** [comment]
> Wouldn't it be better to leave to steps to get docker rootless up to the documentation for docker? Under Ubuntu the rootless stuff can be installed via repository for example.

Yes, the official documentation is linked as well where you can see how to do that for each distro. But honestly, I dislike having to document every specific speciality of each distro here...

**Comment by szaimen** [comment]
> I thought that maybe only link to dockers documentation and done. Then cover what AiO needs.

Alright. then I remove the commands again 👍

**Comment by Kirk1984** [comment]
> > I thought that maybe only link to dockers documentation and done. Then cover what AiO needs.
> 
> Alright. then I remove the commands again 👍

> I removed it. Does it look better now? :)

Looks good to me 👍

**Comment by szaimen** [comment]
> Looks good to me 👍

Great, thanks! 

Let's wait for @evilaliv3 then who promised to test this, too :)

**Pull request merged**
