### PR TITLE
caddy - a bugfix and some improvements

### PR DESCRIPTION
**Pull request by szaimen**
Fix https://github.com/nextcloud/all-in-one/issues/2566

### CODE REVIEW

**Comment by szaimen** [comment]
Todo: think about leaving nextcloud in internal dir and not copying it to the import dir. Then maybe also create an empty file in therr in order to sipence the warning?

**Review by arunas-smala — APPROVED** [review]
it works

**Review by DO6FP — APPROVED** [review]
Fixes the issue #2566 successfully.

**Comment by Zoey2936** [comment]
> Or maybe revert back to one caddyfile and one import statement?

I think that would be the best way, from my perspective, but beside this, do you think, you can release this patch today?

**Comment by szaimen** [comment]
> I think that would be the best way, from my perspective, but beside this, do you think, you can release this patch today?

Thanks for the feedback! I'll try...

**Pull request merged**
