### PR TITLE
Fix migration doc by changing PGDP_PASS to PG_PASSWORD

### PR DESCRIPTION
**Pull request by ninoppp**
you're exporting PG_PASSWORD  but creating a user with PGDP_PASS.

### CODE REVIEW

**Review by szaimen — COMMENTED** [review]
Good catch, thanks! But it needs to be changed in line 45 too, afaics.

**Comment by szaimen** [comment]
Hi @ninoppp,
 unfortunately I don't have push rights to your branch. Can you please allow maintainers to push to the branch and/or fix the remaining place?
Thank you! :)

**Comment by ninoppp** [comment]
Hey @szaimen 
Tbh, this is my first time doing a PR on github. Would you mind sending me a link on how to commit something from my branch? I literally just clicked on "edit page" in github to create this request.

If you don't have a link that's also fine, I'll figure it out myself :)

**Comment by szaimen** [comment]
Just edit this file: https://github.com/ninoppp/all-in-one/blob/patch-2/migration.md once again and it should work :)

**Comment by szaimen** [comment]
Here is a better link to this: https://github.com/ninoppp/all-in-one/edit/patch-2/migration.md

**Review by szaimen — APPROVED** [review]
I was able to fix it myself using the web interface.

Thanks for the PR, @ninoppp! :)

**Comment by ninoppp** [comment]
Ah well thanks for doing it @szaimen :) Will learn to do proper requests once I get around.

**Pull request merged**
