### PR TITLE
database-restore: only get the first match

### PR DESCRIPTION
**Pull request by szaimen**
Fix https://github.com/nextcloud/all-in-one/discussions/4849#discussioncomment-9828253

### CODE REVIEW

**Comment by ralfrupf1976** [comment]
Thank you - do I understand right, I just have to wait for the fix - it will be posted here, right?

**Comment by szaimen** [comment]
> Thank you - do I understand right, I just have to wait for the fix - it will be posted here, right?

I'll inform you once it is available in the beta channel. Probably next tuesday...

**Comment by szaimen** [comment]
This is now released with v9.1.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel

**Comment by ralfrupf1976** [comment]
I just updated to version 9.1.0 and everything works fine again! Thank you

**Pull request merged**
