### PR TITLE
adjust macOS docs about DOCKER_SOCKET_PATH

### PR DESCRIPTION
**Pull request by szaimen**
Fix https://github.com/nextcloud/all-in-one/discussions/1801

Signed-off-by: Simon L <szaimen@e.mail.de>

### CODE REVIEW

**Comment by szaimen** [comment]
@RetroYogi, does this look good to you? :)

**Comment by RetroYogi** [comment]
> @RetroYogi, does this look good to you? :)

It's kind of an exception to an exception, but it's understandable :)

**Comment by szaimen** [comment]
> It's kind of an exception to an exception, but it's understandable :)

yeah, I am also really confused... 😅

But good that it seems to work which was confirmed by you 👍

**Comment by szaimen** [comment]
> can it not be the default value and keep unset?

yes, it could. However for current instances that may have the wrong value it would need to be set back to the default value as otherwise it will use the old value when simply removing it...

**Comment by szaimen** [comment]
Adjusted, please have another look

**Review by Zoey2936 — APPROVED** [review]

**Comment by szaimen** [comment]
Thanks Zoey! :)

**Pull request merged**
