### PR TITLE
Add documentation on migrating using the borg backup

### PR DESCRIPTION
**Pull request by tofuwabohu**
The migration guide lacks the info that the easiest way is by using the included borg backup. I added a guide on how to migrate this way.

I'm not sure on the distinction on the already described "manual" process, maybe there's a better title/structure. When I looked for options on migration, I was a bit intimidated by the manual process and therefore wanted to make sure the easy option is accessible.

### CODE REVIEW

**Comment by szaimen** [comment]
Hi, thanks for your PR!

Currently migration.md describes how to migrate from different Nextcloud installations to AIO. Maybe we shoud make this more clear?

Also, I would probably put your guide under this section somewhere: https://github.com/nextcloud/all-in-one?tab=readme-ov-file#backup-solution

**Comment by tofuwabohu** [comment]
Feel free to put it where you think it fits best. The migration guide is the first thing that shows up on all searches I tried similar to `nextcloud aio migrate to new server`, followed by links to help.nextcloud.com that mention the borg solution. But maybe if we add a different (sub)header, like "migrate nextcloud aio to a different server", websearches will link to that eventually.

**Comment by szaimen** [comment]
> Feel free to put it where you think it fits best. The migration guide is the first thing that shows up on all searches I tried similar to `nextcloud aio migrate to new server`, followed by links to help.nextcloud.com that mention the borg solution. But maybe if we add a different (sub)header, like "migrate nextcloud aio to a different server", websearches will link to that eventually.

Thanks! I did an attempt to this with https://github.com/nextcloud/all-in-one/pull/5570/commits/0598b10f2ebce699ccf6a9151c2ecd2d15966c65. I hope this works for you? :)

**Review by szaimen — APPROVED** [review]
LGTM. Thanks a lot! 😊

**Comment by tofuwabohu** [comment]
Cool, thanks!

**Pull request merged**
