### PR TITLE
update opcache settings

### LINKED ISSUE #192: adjust opcache settings
After several hours (about 10-12 hours) I have the following warning in the settings overview:

`The PHP OPcache module is not properly configured:

    The OPcache interned strings buffer is nearly full. To assure that repeating strings can be effectively cached, it is recommended to apply opcache.interned_strings_buffer to your PHP configuration with a value higher than 8.`

When I stop and restart the containers, the warning is gone.

### PR DESCRIPTION
**Pull request by szaimen**
Fix #192

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by szaimen** [comment]
@MichaIng does this look good to you or do wee need to keep setting opcache.interned_strings_buffer to a higher value than 8?

**Comment by MichaIng** [comment]
Generally looks fine, given that the other settings are PHP defaults anyway. Is there a way for users to pass overrides for PHP settings, i.e. that there is the possibility to increase interned strings buffer when needed? Else probably using `16` to mute the warning in more cases is reasonable. The interned strings buffer is allocated as part of the 128 MiB overall OPcache size, and given that Nextcloud is using only something between 32 and 64 MiB, there is not an issue with allocation some more for the interned strings buffer.

**Comment by szaimen** [comment]
Thanks for your review and answer! Since there is currently no way to adjust this for the user, I'll use 16 as value for the opcache.interned_strings_buffer.

**Comment by juliushaertl** [comment]
Makes sense, thanks also for the good insight on the issue @MichaIng 

Should we maybe also adapt our default recommendations in the documentation then a bit?

**Review by juliushaertl — APPROVED** [review]

**Comment by szaimen** [comment]
Thanks for the review julius!

**Comment by szaimen** [comment]
> Should we maybe also adapt our default recommendations in the documentation then a bit?

I think it is already adjusted...

**Comment by MichaIng** [comment]
Since Apache2 is used as webserver, when mod_php (instead of PHP-FPM) is used, a custom config snippet with `php_value opcache.interned_strings_buffer "16"` would be possible as well, when that is possible to pass to the container.

The docs are already adjusted, but we could add the hint that in some cases a higher than default interned strings buffer is required/recommended, in addition to what the admin panel shows. So admins are made aware of this in the first place, respectively can verify that the admin panel warning is not so unexpected when following the link which is shown on the admin panel as well.

**Pull request merged**
