### PR TITLE
coturn container - pin alpine version manually

### PR DESCRIPTION
**Pull request by szaimen**

### CODE REVIEW

**Comment by Zoey2936** [comment]
so you want the build to fail if the version is different, right?

**Comment by szaimen** [comment]
> so you want the build to fail if the version is different, right?

Yes

**Comment by Zoey2936** [comment]
maybe then remove the -r3 since I think dependabot doesn't understand that

**Comment by szaimen** [comment]
> maybe then remove the -r3 since I think dependabot doesn't understand that

good idea

**Comment by szaimen** [comment]
https://github.com/nextcloud/all-in-one/pull/2817

**Pull request merged**
