### PR TITLE
optimize collabora Dockerfile

### PR DESCRIPTION
**Pull request by Zoey2936**

### CODE REVIEW

**Review by szaimen — CHANGES_REQUESTED** [review]
I would keep it like this

**Comment by Zoey2936** [comment]
and why?

**Comment by szaimen** [comment]
becaause DEBIAN_FRONTEND is alreaddy set during hte command so we dont need another arg right?

**Comment by Zoey2936** [comment]
> becaause DEBIAN_FRONTEND is alreaddy set during hte command so we dont need another arg right?

yes, but I prefer using ARG for settings envs while building, but if you want you can close this PR

**Comment by szaimen** [comment]
> > becaause DEBIAN_FRONTEND is alreaddy set during hte command so we dont need another arg right?
> 
> yes, but I prefer using ARG for settings envs while building, but if you want you can close this PR

I see but I think it is not necessary so I would close it

**Pull request closed without merging**
