### PR TITLE
change how permission check setting works

### PR DESCRIPTION
**Pull request by szaimen**
Close https://github.com/nextcloud/all-in-one/discussions/2108

### CODE REVIEW

**Comment by Zoey2936** [comment]
so it is disabled, unless manually enabled?

**Comment by szaimen** [comment]
> so it is disabled, unless manually enabled?

the permission check gets now always skipped upon initial install but after initial install the permission check gets enabled again if not skipped via environmental variable.

**Comment by Zoey2936** [comment]
> > so it is disabled, unless manually enabled?
> 
> the permission check gets now always skipped upon initial install but after initial install the permission check gets enabled again if not skipped via environmental variable.

but why?

**Comment by szaimen** [comment]
> but why?

Because if we don't do this the initial installation will fail if you e.g. have added 777 permisions. The check in the container is checking if it can write but nextcloud installation will fail because permissions are too open. So I'd rather skip the permission check of Nextcloud always during the initial installationi since we have our own check in place. Afterwards I add the permission check again if it should not get skipped so that it is shown in the admin overview and you can do needed changes afterwarrds.

**Review by Zoey2936 — APPROVED** [review]

**Comment by szaimen** [comment]
Thanks! :)

**Pull request merged**
