### PR TITLE
add further note about cloudflare and domain validation

### PR DESCRIPTION
**Pull request by szaimen**
Signed-off-by: Simon L <szaimen@e.mail.de>

### CODE REVIEW

**Comment by szaimen** [comment]
@Zoey2936 btw, there are now already so many problems with Cloudflare that I slowly get tired of this...

**Comment by Zoey2936** [comment]
> @Zoey2936 btw, there are now already so many problems with Cloudflare that I slowly get tired of this...

Yes... we could also mention this: https://github.com/nextcloud/all-in-one/discussions/1697

**Comment by szaimen** [comment]
> Yes... we could also mention this: #1697

indeed: https://github.com/nextcloud/all-in-one/pull/1770

**Comment by Zoey2936** [comment]
And stun/talk also wont work since cloudflare dont proxy (port 3478) them, we should mention that in the talk settings, the domain needs to be replaced with the external hostname / external ip of the server

**Comment by szaimen** [comment]
> And stun/talk also wont work since cloudflare dont proxy (port 3478) them, we should mention that in the talk settings, the domain needs to be replaced with the external hostname / external ip of the server

right. Let me create an additional PR.

**Review by Zoey2936 — APPROVED** [review]

**Pull request merged**
