### PR TITLE
Update reverse-proxy.md

### PR DESCRIPTION
**Pull request by foegra**
after Nextcloud 29 - new configuration has to be used for Caddyfile

### CODE REVIEW

**Review by Zoey2936 — COMMENTED** [review]
should be added to the AIO caddyfile, not the reverse proxy guide

**Comment by szaimen** [comment]
> should be added to the AIO caddyfile, not the reverse proxy guide

Already done via https://github.com/nextcloud/all-in-one/pull/4774 and released with v9.0.0 Beta

**Comment by foegra** [comment]
> should be added to the AIO caddyfile, not the reverse proxy guide

Where is that located?

**Comment by foegra** [comment]
> should be added to the AIO caddyfile, not the reverse proxy guide

Big pardon - but why Caddyfile is included in the AIO installation?

**Pull request closed without merging**
