### PR TITLE
Added a replace statement for the database-dump.sql

### PR DESCRIPTION
**Pull request by FaySmash**
Without this statement, only the comments in the database-dump.sql which state the table owner get replaced but from not the important ALTER TABLE statement itself.

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
LGTM, thanks!

**Comment by FaySmash** [comment]
> LGTM, thanks!

Actually, looking at it again, I might found an issue. The line
`sed -i 's| OWNER TO nextcloud;$| OWNER TO ncadmin;$|' database-dump.sql`

should be changed to
`sed -i 's| OWNER TO nextcloud;$| OWNER TO ncadmin;|' database-dump.sql`

(removed the second $-symbol)

**Comment by szaimen** [comment]
Can you create a follow-up pr?

**Comment by FaySmash** [comment]
> Can you create a follow-up pr?

done: https://github.com/nextcloud/all-in-one/compare/main...FaySmash:all-in-one:patch-1

(navigating GitHub is a pita..)

**Pull request merged**
