### PR TITLE
exclude nextcloud and audit log in backup due to GPDR reasons

### PR DESCRIPTION
**Pull request by szaimen**

### CODE REVIEW

**Review by Zoey2936 — APPROVED** [review]

**Comment by Zoey2936** [comment]
borg create: error: argument ARCHIVE: "/nextcloud_aio_volumes/nextcloud_aio_nextcloud/data/nextcloud.log.1": No archive specified

**Comment by Zoey2936** [comment]
running `rm /var/lib/docker/volumes/nextcloud_aio_nextcloud/_data/data/nextcloud.log.1` fixed it for me

**Comment by szaimen** [comment]
Still this needs to work. I'll have a look at this tomorrow.

**Comment by szaimen** [comment]
Thanks for reporting!

**Comment by szaimen** [comment]
This is now fixed with v4.6.1 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel

**Comment by Zoey2936** [comment]
worked now for me

**Comment by szaimen** [comment]
Thanks for checking! :)

**Pull request merged**
