### PR TITLE
add nginx-proxy-manager to the reverse proxy documentation

### PR DESCRIPTION
**Pull request by szaimen**
Close #681

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by szaimen** [comment]
@2020Sanoj does this look good to you? :)

**Comment by 2020Sanoj** [comment]
Maybe these pictures are better:

grafik
grafik
grafik
(to this picture, they can also use custom uploaded / existing certificates in the selection or use wildcard certificates they generated over a DNS challenge)
grafik


And what about also mention that the nginx proxy manager can also be started in host mode with adding, this to the compose file, if the people use docker compose for the npm:
`    network_mode: host`

And I think you won't will add this, but this would be the details page I use for the aio dashboard, the other config pages in the npm are the same. (it is working, only there is currently #673 which is not working). Maybe this will be useful someday.
grafik

**Comment by 2020Sanoj** [comment]
Yes, but if you mention that `<your-nc-domain>` needs to be changed, why not also mention, that `<you>@<your-mail-provider-domain>` needs to be changed?
But beside this it looks good and should be understandable for everyone using the npm.

**Comment by 2020Sanoj** [comment]
Looks good now for me

**Comment by szaimen** [comment]
> Looks good now for me

thanks! I'll merge as soon as CI is done :)

**Pull request merged**
