### PR TITLE
add an explanation of `--sig-proxy=false`

### PR DESCRIPTION
**Pull request by szaimen**
Close https://github.com/nextcloud/all-in-one/issues/1734

Signed-off-by: Simon L <szaimen@e.mail.de>

### CODE REVIEW

**Comment by szaimen** [comment]
@Verhoeckx does this make point 1 of your list a bit clearer? :)

**Review by ManOki — APPROVED** [review]
LGTM

**Comment by szaimen** [comment]
Thanks for the approval! :)

**Comment by Verhoeckx** [comment]
> @Verhoeckx does this tick point 1 of your list? :)

Yes, it does :blush: !

**Pull request merged**
