### PR TITLE
nextcloud - improve healthcheck

### PR DESCRIPTION
**Pull request by szaimen**
Close part of https://github.com/nextcloud/all-in-one/discussions/3197

### CODE REVIEW

**Comment by szaimen** [comment]
@frederikb96 does this look good to you?

**Comment by frederikb96** [comment]
> @frederikb96 does this look good to you? :)

Look's nice, thanks a lot for such a fast reply and fix :)

**Review by Zoey2936 — CHANGES_REQUESTED** [review]
I would instead change the start-period https://docs.docker.com/engine/reference/builder/#healthcheck

**Comment by szaimen** [comment]
> I would instead change the start-period https://docs.docker.com/engine/reference/builder/#healthcheck

Good idea, thanks!

**Review by Zoey2936 — APPROVED** [review]

**Comment by szaimen** [comment]
Hm... I wonder how to fix the docker Lint workflow...

**Comment by szaimen** [comment]
Seems like we need another patch: https://github.com/replicatedhq/dockerfilelint/pull/167/files

**Pull request merged**
